apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-db-pvc
  labels:
    app: forgejo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
