# AgentMemory Composite Resource Definition (XRD)
# Defines the schema for agent memory provisioning
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xagentmemories.lornu.ai
  labels:
    lornu.ai/managed-by: crossplane
    lornu.ai/component: agentmemory
spec:
  group: lornu.ai
  names:
    kind: XAgentMemory
    plural: xagentmemories
  claimNames:
    kind: AgentMemory
    plural: agentmemories

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - provider
                - size
              properties:
                provider:
                  type: string
                  description: Cloud provider (azure, gcp, aws)
                  enum:
                    - azure
                    - gcp
                    - aws
                size:
                  type: string
                  description: Storage size
                  enum:
                    - small   # 10Gi
                    - medium  # 50Gi
                    - large   # 100Gi
                tier:
                  type: string
                  description: Performance tier
                  default: standard
                  enum:
                    - standard
                    - premium
                region:
                  type: string
                  description: Cloud region
                  default: eastus2
            status:
              type: object
              properties:
                connectionSecret:
                  type: string
                  description: Name of the connection secret
                endpoint:
                  type: string
                  description: Database endpoint
                ready:
                  type: boolean
                  description: Whether the resource is ready
