apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-promote
  namespace: tekton-pipelines
spec:
  params:
    - name: image
      type: string
      description: "Image name to build (registry/repo:tag)"
    - name: dockerfile
      type: string
      default: ./Dockerfile
    - name: context
      type: string
      default: .
    - name: aws-region
      type: string
      description: "AWS region for ECR auth"
    - name: aws-role-arn
      type: string
      default: ""
    - name: aws-web-identity-token-path
      type: string
      default: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: aws-target
      type: string
      default: ""
    - name: azure-target
      type: string
      default: ""
    - name: azure-client-id
      type: string
      default: ""
    - name: azure-tenant-id
      type: string
      default: ""
    - name: azure-federated-token-path
      type: string
      default: /var/run/secrets/azure/tokens/azure-identity-token
    - name: gcp-target
      type: string
      default: ""
    - name: gcp-token-path
      type: string
      default: /var/run/secrets/tokens/gcp-token
  taskRunTemplate:
    serviceAccountName: tekton-promoter-sa
  workspaces:
    - name: source
  tasks:
    - name: build
      taskRef:
        name: build-image-artifact
      params:
        - name: image
          value: $(params.image)
        - name: dockerfile
          value: $(params.dockerfile)
        - name: context
          value: $(params.context)
      workspaces:
        - name: source
          workspace: source
    - name: promote
      taskRef:
        name: cloud-promote-artifact
      params:
        - name: source-image
          value: $(tasks.build.results.image-ref)
        - name: aws-region
          value: $(params.aws-region)
        - name: aws-role-arn
          value: $(params.aws-role-arn)
        - name: aws-web-identity-token-path
          value: $(params.aws-web-identity-token-path)
        - name: aws-target
          value: $(params.aws-target)
        - name: azure-target
          value: $(params.azure-target)
        - name: azure-client-id
          value: $(params.azure-client-id)
        - name: azure-tenant-id
          value: $(params.azure-tenant-id)
        - name: azure-federated-token-path
          value: $(params.azure-federated-token-path)
        - name: gcp-target
          value: $(params.gcp-target)
        - name: gcp-token-path
          value: $(params.gcp-token-path)
      runAfter:
        - build
