apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-promoter-sa
  namespace: tekton-pipelines
  annotations:
    azure.workload.identity/use: "true"
    # Set via environment-specific patch or overlay.
    azure.workload.identity/client-id: ""
