apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-promoter-sa
  namespace: tekton-pipelines
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: REPLACE_WITH_AZURE_CLIENT_ID
