apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: tekton-pipelines
  labels:
    lornu.ai/environment: production
    lornu.ai/component: tekton
    lornu.ai/managed-by: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
  namespace: tekton-pipelines
  labels:
    lornu.ai/environment: production
    lornu.ai/component: tekton
    lornu.ai/managed-by: flux
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
  namespace: tekton-pipelines
  labels:
    lornu.ai/environment: production
    lornu.ai/component: tekton
    lornu.ai/managed-by: flux
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
