apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: flux-gitrepo-binding
  namespace: tekton-pipelines
  labels:
    lornu.ai/component: tekton
    lornu.ai/managed-by: flux
spec:
  params:
    - name: revision
      value: $(body.metadata.revision)
