//! Shared types for cyber/security agents
//!
//! This module contains common types used across the Zero Trust
//! and other security-focused agents.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Severity levels for security insights
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum InsightSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// Type of correction action to propose
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CorrectionType {
    /// Delete an unused IAM role entirely
    DeleteRole,
    /// Remove specific unused permissions from a role
    ShrinkRole,
    /// Rotate a stale secret
    RotateSecret,
    /// Convert long-lived credential to ephemeral token
    ConvertToEphemeral,
}

/// IAM insight from GCP IAM Recommender API
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IamInsight {
    /// Unique insight ID from GCP
    pub insight_id: String,
    /// Service account email
    pub service_account: String,
    /// Days since last permission exercise
    pub days_inactive: u32,
    /// Permissions that were never used
    pub unused_permissions: Vec<String>,
    /// Severity level based on risk
    pub severity: InsightSeverity,
    /// Timestamp of insight generation
    pub generated_at: DateTime<Utc>,
}

/// Correction action generated by the Zero Trust agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IamCorrection {
    /// Unique correction ID
    pub id: Uuid,
    /// Type of correction
    pub correction_type: CorrectionType,
    /// Service account, role, or secret affected
    pub target: String,
    /// Current state (JSON representation)
    pub current_state: serde_json::Value,
    /// Proposed state (JSON representation)
    pub proposed_state: serde_json::Value,
    /// Rationale for the correction
    pub rationale: String,
    /// Risk level of NOT applying this correction
    pub risk_level: InsightSeverity,
    /// CDK8s file path to update (if applicable)
    pub cdk8s_file_path: Option<String>,
    /// Timestamp
    pub created_at: DateTime<Utc>,
}

/// Secret rotation request for Google Secret Manager
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretRotationRequest {
    /// Secret ID in Google Secret Manager
    pub secret_id: String,
    /// Project ID
    pub project_id: String,
    /// Age in days
    pub age_days: u32,
    /// Whether rotation was triggered
    pub rotation_triggered: bool,
    /// Timestamp
    pub requested_at: DateTime<Utc>,
}

/// Request to convert long-lived credential to ephemeral token
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EphemeralTokenRequest {
    /// Service account to convert
    pub service_account: String,
    /// Current credential type (json_key, api_key, etc.)
    pub current_credential_type: String,
    /// Target token type (workload_identity, oidc, etc.)
    pub target_token_type: String,
    /// Expiry duration for ephemeral token in seconds
    pub token_ttl_seconds: u32,
}

/// Result of a Zero Trust scan operation
#[derive(Debug, Serialize)]
pub struct ZeroTrustScanResult {
    /// Total service accounts scanned
    pub accounts_scanned: u32,
    /// Insights discovered
    pub insights: Vec<IamInsight>,
    /// Corrections proposed
    pub corrections: Vec<IamCorrection>,
    /// Secrets requiring rotation
    pub secrets_to_rotate: Vec<SecretRotationRequest>,
    /// Long-lived credentials to convert
    pub ephemeral_conversions: Vec<EphemeralTokenRequest>,
    /// Scan duration in milliseconds
    pub scan_duration_ms: u64,
    /// Timestamp
    pub completed_at: DateTime<Utc>,
}

/// Learning pattern stored in Qdrant for shrink decisions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShrinkPattern {
    /// Unique pattern ID
    pub id: Uuid,
    /// Embedding signature of the permission set
    pub permission_signature: String,
    /// Service type (e.g., "cloudrun", "gke", "cloudsql")
    pub service_type: String,
    /// Permissions that were safely removed
    pub removed_permissions: Vec<String>,
    /// Number of successful removals without incident
    pub success_count: u32,
    /// Number of times removal caused issues (rollbacks)
    pub rollback_count: u32,
    /// Created timestamp
    pub created_at: DateTime<Utc>,
    /// Last used timestamp
    pub last_used_at: DateTime<Utc>,
}

impl ShrinkPattern {
    /// Calculate confidence score for this pattern
    ///
    /// Returns a value between 0.0 and 1.0 representing the success rate.
    pub fn confidence_score(&self) -> f32 {
        let total = self.success_count + self.rollback_count;
        if total == 0 {
            0.0
        } else {
            self.success_count as f32 / total as f32
        }
    }
}

/// Result of a remediation PR creation
#[derive(Debug, Serialize)]
pub struct RemediationResult {
    /// Whether the operation succeeded
    pub success: bool,
    /// PR number if created
    pub pr_number: Option<u64>,
    /// PR URL if created
    pub pr_url: Option<String>,
    /// Branch name used
    pub branch_name: String,
    /// Number of corrections applied
    pub corrections_applied: u32,
    /// Status message
    pub message: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shrink_pattern_confidence_with_successes() {
        let pattern = ShrinkPattern {
            id: Uuid::new_v4(),
            permission_signature: "test@project.iam.gserviceaccount.com".to_string(),
            service_type: "cloudrun".to_string(),
            removed_permissions: vec!["storage.objects.list".to_string()],
            success_count: 9,
            rollback_count: 1,
            created_at: Utc::now(),
            last_used_at: Utc::now(),
        };

        assert!((pattern.confidence_score() - 0.9).abs() < 0.001);
    }

    #[test]
    fn test_shrink_pattern_confidence_empty() {
        let pattern = ShrinkPattern {
            id: Uuid::new_v4(),
            permission_signature: "new@project.iam.gserviceaccount.com".to_string(),
            service_type: "gke".to_string(),
            removed_permissions: vec![],
            success_count: 0,
            rollback_count: 0,
            created_at: Utc::now(),
            last_used_at: Utc::now(),
        };

        assert_eq!(pattern.confidence_score(), 0.0);
    }

    #[test]
    fn test_shrink_pattern_confidence_all_failures() {
        let pattern = ShrinkPattern {
            id: Uuid::new_v4(),
            permission_signature: "bad@project.iam.gserviceaccount.com".to_string(),
            service_type: "cloudsql".to_string(),
            removed_permissions: vec!["iam.roles.delete".to_string()],
            success_count: 0,
            rollback_count: 5,
            created_at: Utc::now(),
            last_used_at: Utc::now(),
        };

        assert_eq!(pattern.confidence_score(), 0.0);
    }
}
