apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: forgejo
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://__AZURE_KEYVAULT_NAME__.vault.azure.net"
      serviceAccountRef:
        name: forgejo-eso-sa
