#!/usr/bin/env bun
/**
 * Generates the Tekton Task and Pipeline YAML files.
 *
 * This script defines the Tekton resources as TypeScript objects,
 * then serializes them to YAML. This allows for better type safety,
 * composition, and keeps all pipeline logic in TypeScript.
 *
 * To run:
 *   bun run workflow:tekton:generate
 */

import * as fs from "fs";
import * as path from "path";
import yaml from "js-yaml";
import { versions } from "./versions";

// Helper to define multi-line shell scripts in a clean way.
const script = (strings: TemplateStringsArray, ...values: any[]) => {
  const raw = String.raw({ raw: strings }, ...values);
  return raw.trim().replace(/  +/g, " "); // Remove extra indentation
};

const fileHeader = `# This file is generated by ci/generate-tekton-workflow.ts. DO NOT EDIT MANUALLY.\n\n`;

/**
 * Tekton Task Definition
 */
const daggerTask = {
  apiVersion: "tekton.dev/v1",
  kind: "Task",
  metadata: {
    name: "dagger-pipeline",
  },
  spec: {
    description: "Runs the lornu.ai Dagger pipeline based on the git branch and event type.",
    params: [
      { name: "branch", description: "The git branch name.", type: "string" },
      { name: "github-event-name", description: "The raw GitHub event name (e.g., 'push', 'pull_request')", type: "string", default: "push" },
    ],
    workspaces: [
      { name: "source", description: "The workspace containing the source code." },
    ],
    steps: [
      {
        name: "run-dagger-pipeline",
        image: `${versions.images.ciRunner}:latest`, // Use our custom, pre-built image
        workingDir: "$(workspaces.source.path)",
        script: script`
          #!/usr/bin/env sh
          set -e
          echo "🚀 Running Dagger pipeline for branch: $(params.branch)"
          dagger run bun ci/dagger.ts --branch "$(params.branch)" --github-event-name "$(params.github-event-name)" --source .
        `,
      },
    ],
    sidecars: [
      {
        name: "dagger-engine",
        image: versions.images.dind,
        securityContext: {
          privileged: true,
        },
        env: [
          { name: "DOCKER_TLS_CERTDIR", value: "" }, // Disable TLS for local communication
        ],
      },
    ],
  },
};

/**
 * Tekton Pipeline Definition
 */
const lornuAiPipeline = {
  apiVersion: "tekton.dev/v1",
  kind: "Pipeline",
  metadata: {
    name: "lornu-ai-ci",
  },
  spec: {
    description: "CI pipeline for the lornu.ai repository. Clones the repo and runs the Dagger pipeline.",
    params: [
      { name: "repo-url", type: "string", description: "The git repository URL." },
      { name: "branch-name", type: "string", description: "The git branch to checkout." },
      { name: "github-event-name", type: "string", description: "The raw GitHub event name (e.g., 'push', 'pull_request')", default: "push" },
    ],
    workspaces: [
      { name: "shared-data", description: "Workspace for source code." },
    ],
    tasks: [
      {
        name: "fetch-source",
        taskRef: { name: "git-clone" },
        workspaces: [{ name: "output", workspace: "shared-data" }],
        params: [
          { name: "url", value: "$(params.repo-url)" },
          { name: "revision", value: "$(params.branch-name)" },
          { name: "depth", value: "0" }, // Fetch all history for accurate branch info
        ],
      },
      {
        name: "run-dagger-pipeline",
        runAfter: ["fetch-source"],
        taskRef: { name: "dagger-pipeline" },
        workspaces: [{ name: "source", workspace: "shared-data" }],
        params: [
          { name: "branch", value: "$(params.branch-name)" }, // This is correct
          { name: "github-event-name", value: "$(params.github-event-name)" }, // Pass the raw event name
        ],
      },
    ],
  },
};

// Generate and write files
const taskOutputPath = path.resolve(__dirname, "tekton/dagger-task.yaml");
fs.writeFileSync(taskOutputPath, fileHeader + yaml.dump(daggerTask));
console.log(`✅ Tekton Task generated at: ${taskOutputPath}`);

const pipelineOutputPath = path.resolve(__dirname, "tekton/lornu-ai-pipeline.yaml");
fs.writeFileSync(pipelineOutputPath, fileHeader + yaml.dump(lornuAiPipeline));
console.log(`✅ Tekton Pipeline generated at: ${pipelineOutputPath}`);