#!/usr/bin/env bun
/**
 * Generates the .github/workflows/dagger-pipeline.yml file.
 *
 * This script defines the GitHub Actions workflow as a TypeScript object,
 * then serializes it to YAML. This allows for better type safety,
 * composition, and keeps all pipeline logic in TypeScript.
 *
 * To run:
 *   bun run workflow:generate
 */

import * as fs from "fs";
import * as path from "path";
import yaml from "js-yaml";
import { versions } from "./versions";

// Helper to define multi-line shell scripts in a clean way.
const script = (strings: TemplateStringsArray, ...values: any[]) => {
  const raw = String.raw({ raw: strings }, ...values);
  return raw.trim().replace(/  +/g, " "); // Remove extra indentation
};

const workflow = {
  name: "Dagger Pipeline",
  on: {
    push: {
      branches: ["feat/**", "infra/**", "agent/**", "ta"],
    },
    pull_request: {
      branches: ["ta"],
    },
    workflow_dispatch: {
      inputs: {
        branch: {
          description: "Branch name to simulate",
          required: true,
          default: "feat/test",
        },
      },
    },
  },
  jobs: {
    "dagger-pipeline": {
      name: "Dagger Pipeline: ${{ github.ref_name }}",
      "runs-on": "ubuntu-latest",
      steps: [
        {
          name: "Checkout",
          uses: "actions/checkout@v4",
        },
        {
          name: "Setup Bun",
          uses: "oven-sh/setup-bun@v2",
          with: {
            "bun-version": versions.bun,
          },
        },
        {
          name: "Install dependencies",
          run: "bun install",
        },
        {
          name: "Install Dagger CLI",
          uses: "dagger/dagger-for-github@v7",
          with: {
            version: versions.dagger,
          },
        },
        {
          name: "Run Dagger Pipeline",
          env: {
            DAGGER_LOG_FORMAT: "plain",
            DAGGER_LOG_LEVEL: "info",
          },
          run: script`
            bun ci/dagger.ts \\
              --branch "\${{ github.ref_name }}" \\
              --base-branch "\${{ github.base_ref || 'ta' }}" \\
              --github-event-name "\${{ github.event_name }}"
          `,
        },
        {
          name: "Cleanup agent sandbox (on branch delete)",
          if: "github.event_name == 'delete' && startsWith(github.ref, 'refs/heads/agent/')",
          run: script`
            echo "🗑️  Branch deleted, cleaning up agent sandbox..."
            # This would trigger sandbox deletion via webhook or scheduled job
            # For now, log the action
            echo "Sandbox cleanup triggered for: \${{ github.ref }}"
          `,
        },
      ],
    },
  },
};

const yamlString = yaml.dump(workflow, {
  lineWidth: -1, // No line wrapping
  quotingType: '"',
});

const outputPath = path.resolve(__dirname, "../.github/workflows/dagger-pipeline.yml");

const fileHeader = `# This file is generated by ci/generate-workflow.ts. DO NOT EDIT MANUALLY.\n\n`;

fs.writeFileSync(outputPath, fileHeader + yamlString);

console.log(`✅ GitHub Actions workflow generated at: ${outputPath}`);